spring:
  application:
    name: taskmanager
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: ${APP_JWT_SECRET:}
    expiration: 3600000 # 1 hour

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
