server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SPRING_SERVER_CONTEXT_PATH:/api}
  allowed-origins: ${SPRING_SERVER_ALLOWED_ORIGINS:http://localhost:4200}

spring:
  application:
    name: taskmanager
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL:true}

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-local-dev-secret-32-chars-min}
    expiration: 3600000 # 1 hour

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.reddy.taskmanager: ${LOGGING_LEVEL_TASK_MANAGER:DEBUG}
    org:
      springframework: ${LOGGING_LEVEL_SPRINGFRAMEWORK:INFO}
      hibernate:
        orm:
          connections:
            pooling: ${LOGGING_LEVEL_HIBERNATE_POOLING:WARN}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
